app:
    resource: '@AppBundle/Controller/'
    type: annotation

home_login:
    path:     /
    defaults: { _controller: AppBundle:Default:login }

add_task:
    path:     /task/add
    defaults: { _controller: AppBundle:Default:add }

edit_task:
    path:     /task/edit/{task_id}
    defaults: { _controller: AppBundle:Default:edit }
    requirements:
        task_id: '\d+'

delete_task:
    path:     /task/delete/{task_id}
    defaults: { _controller: AppBundle:Default:delete }
    requirements:
        task_id: '\d+'

done_task:
    path:     /task/ajaxTaskDone
    defaults: { _controller: AppBundle:Default:ajaxTaskDone }
    methods: [post]

tasks:
    path:     /tasks
    defaults: { _controller: AppBundle:Default:show }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile